backend:
  name: github
  repo: 101hawn/ecsu
  base_url: https://nh487.user.srcf.net
  branch: cms

  
collections:
    - label: "Pages"
      name: "pages"
      editor:
        preview: false
      files:
        - label: "Home"
          name: "home"
          file: "content/pages/home.md"
          fields:
            - label: What does ECSU do
              name: ecsu_does
              widget: list
              fields:
                - {label: Title, name: title, widget: string}
                - {label: Icon, name: icon, widget: string}
                - {label: Description, name: description, widget: string}
            - label: What's here
              name: whats_here
              widget: list
              fields:
                - {label: Title, name: title, widget: string}
                - {label: Image, name: image, widget: image}
                - {label: Url, name: url, widget: string}
                - {label: Description, name: description, widget: string}
                
    - name: "exec" # Used in routes, e.g., /admin/collections/blog
      label: "Exec" # Used in the UI
      folder: "content/exec" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Email", name: "email", widget: "string"}
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Image", name: "image", widget: "image", required: false}
        - {label: "Bio", name: "body", widget: "markdown", required: false}
      editor:
        preview: false

    - name: "whatson"
      label: "What's On"
      folder: "content/whatson"
      create: true
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish date", name: "pubdate", widget: "date", hidden: true}
        - {label: "Event time", name: "datetime", widget: "datetime"}
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Content", name: "body", widget: "markdown"}
      editor:
        preview: false

    - name: "societies"
      label: "Societies"
      label_singular: "Society"
      folder: "content/societies"
      create: true
      fields: # The fields for each document, usually in front matter
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Image", name: "image", widget: "image", required: false}
        - {label: "Description", name: "body", widget: "markdown", required: false}
      editor:
        preview: false

    - name: "welfare"
      label: "Welfare information"
      folder: "content/welfare"
      create: true
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
        - {label: "Image", name: "image", widget: "image", required: false}
        - {label: "Content", name: "body", widget: "markdown", required: false}
      editor:
        preview: false
        
    - name: "info"
      label: "General information"
      folder: "content/info"
      create: true
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
        - {label: "Image", name: "image", widget: "image", required: false}
        - {label: "Content", name: "body", widget: "markdown", required: false}
      editor:
        preview: false
        
    - name: "prospective"
      label: "Prospective students"
      folder: "content/prospective"
      create: true
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
        - {label: "Image", name: "image", widget: "image", required: false}
        - {label: "Content", name: "body", widget: "markdown", required: false}
      editor:
        preview: false

        
        
    - name: "blogs"
      label: "Blogs"
      label_singular: "Blog"
      folder: "content/blogs"
      slug: "{{slug}}"
      create: true
      fields:
        - {label: "Name", name: "title", widget: "string"}
        - {label: "Description", name: "description", widget: "string"}
      editor:
        preview: false

    - name: "posts"
      label: "Blog posts"
      label_singular: "Blog post"
      folder: "content/posts"
      slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
      create: true
      fields:
        - {label: "Blog", name: "blog", widget: "relation", collection: "blogs", searchFields: ["title"], valueField: "title"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
        - {label: "Image", name: "image", widget: "image", required: false}
        - {label: "Content", name: "body", widget: "markdown", required: false}
      editor:
        preview: false

    - name: "rooms"
      label: "Rooms"
      label_singular: "Room"
      folder: "content/rooms"
      create: true
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Location", name: "location", widget: "relation", collection: "room_locations", searchFields: ["title"], valueField: "title"}
        - {label: "Grade", name: "grade", widget: "number"}
        - label: "Images"
          name: "images"
          widget: "list"
          field: {label: Image, name: image, widget: image}
          required: false
        - label: "Network"
          name: "network"
          widget: "select"
          options: ["Wireless Only", "Wired and Wireless"]
        - label: "Has a basin?"
          name: "basin"
          widget: "select"
          options: ["Yes", "No", "En-Suite"]
        - label: "Living room?"
          name: "living_room"
          widget: "select"
          options: ["Yes", "No", "Shared"]
        - label: "CUDN?"
          name: "cudn"
          widget: "boolean"
        - label: "Floor"
          name: "floor"
          widget: "select"     
          options: ["Basement", "Ground", "First", "Second", "Third", "Attic"]
      editor:
        preview: false

    - name: "room_comments"
      label: "Room Comments"
      label_singular: "Room Comment"
      folder: "content/room_comments"
      create: true
      slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
      fields:
        - {label: "Room", name: "title", widget: "relation", collection: "rooms", searchFields: ["title"], valueField: "title"}
        - {label: "Year", name: "year", widget: "string", required: false}
        - {label: "Content", name: "body", widget: "markdown", required: false}
      editor:
        preview: false

    - name: "room_locations"
      label: "Room Locations"
      label_singular: "Room Location"
      folder: "content/room_locations"
      create: true
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description", name: "body", widget: "string"}
        - {label: "Image", name: "image", widget: "image", required: false}
      editor:
        preview: false

                


      



media_folder: "static/images/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: e3ddd3ab91b80df3f0a5